# Context root
server:
  servlet:
    context-path: /readbook

spring:
  mvc:
    static-path-pattern: "/static/**"
  web:
    resources:
      static-locations: "classpath:static/"
      add-mappings: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    # table 생성
    hibernate:
      ddl-auto: create
    # sql show pretty formatter
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/naraDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "12341234"

logging:
  level:
    root: debug
    com.callor.readbook: debug